config:
  description: ArgoCD - Continous Deployment from Git

apps:
- name: argocd
  repoURL: https://argoproj.github.io/argo-helm
  chart: argo-cd
  targetRevision: 3.26.10
  syncWave: "0"
  secrets:
    - name: argocd-secret
      keys:
        - admin.password
        - server.secretkey
        - oidc.auth0.clientSecret
