# List of helm or git repos we want to add to ArgoCD
# Parameters:
# - name: name-of-repo
#   url: https://...
#   type: [default: helm | git]
#
repos:
  argo:
    url: https://argoproj.github.io/argo-helm
  bitnami:
    url: https://charts.bitnami.com/bitnami
  k8s-at-home:
    url: https://k8s-at-home.com/charts
  jetstack:
    url: https://charts.jetstack.io
  heqet:
    url: https://git.nold.in/nold/heqet
    type: git
